// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deleteUsers.sql

package database

import (
	"context"
)

const truncateUsers = `-- name: TruncateUsers :exec
TRUNCATE users
`

func (q *Queries) TruncateUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateUsers)
	return err
}
