// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getUserByName.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserName = `-- name: GetUserName :one
SELECT name from users
    where id = $1
`

func (q *Queries) GetUserName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
