// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: updatePost.sql

package database

import (
	"context"
	"time"
)

const updatePost = `-- name: UpdatePost :exec
UPDATE posts SET
 updated_at = $1, title = $2, description = $3
WHERE url = $4
`

type UpdatePostParams struct {
	UpdatedAt   time.Time
	Title       string
	Description string
	Url         string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.Url,
	)
	return err
}
